matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode10.2
      script:
        - set -o pipefail
        - swift package generate-xcodeproj
        - xcodebuild test -scheme CGPointVector-Package -configuration Debug | xcpretty -c
        - xcodebuild test -scheme CGPointVector-Package -configuration Debug -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone XS" | xcpretty -c
        - xcodebuild test -scheme CGPointVector-Package -configuration Debug -sdk appletvsimulator -destination "platform=tvOS Simulator,name=Apple TV 4K" | xcpretty -c
        - xcodebuild build -scheme CGPointVector-Package -configuration Debug -sdk watchsimulator -destination "platform=watchOS Simulator,name=Apple Watch Series 4 - 44mm" | xcpretty -c
        - xcodebuild test -scheme CGPointVector-Package -configuration Release | xcpretty -c
        - xcodebuild test -scheme CGPointVector-Package -configuration Release -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone XS" | xcpretty -c
        - xcodebuild test -scheme CGPointVector-Package -configuration Release -sdk appletvsimulator -destination "platform=tvOS Simulator,name=Apple TV 4K" | xcpretty -c
        - xcodebuild build -scheme CGPointVector-Package -configuration Release -sdk watchsimulator -destination "platform=watchOS Simulator,name=Apple Watch Series 4 - 44mm" | xcpretty -c
    - os: osx
      language: objective-c
      osx_image: xcode11
      script:
        - set -o pipefail
        - swift package generate-xcodeproj
        - xcodebuild test -scheme CGPointVector-Package -configuration Debug | xcpretty -c
        - xcodebuild test -scheme CGPointVector-Package -configuration Debug -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 11 Pro" | xcpretty -c
        - xcodebuild test -scheme CGPointVector-Package -configuration Debug -sdk appletvsimulator -destination "platform=tvOS Simulator,name=Apple TV 4K" | xcpretty -c
        - xcodebuild build -scheme CGPointVector-Package -configuration Debug -sdk watchsimulator -destination "platform=watchOS Simulator,name=Apple Watch Series 5 - 44mm" | xcpretty -c
        - xcodebuild test -scheme CGPointVector-Package -configuration Release | xcpretty -c
        - xcodebuild test -scheme CGPointVector-Package -configuration Release -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 11 Pro" | xcpretty -c
        - xcodebuild test -scheme CGPointVector-Package -configuration Release -sdk appletvsimulator -destination "platform=tvOS Simulator,name=Apple TV 4K" | xcpretty -c
        - xcodebuild build -scheme CGPointVector-Package -configuration Release -sdk watchsimulator -destination "platform=watchOS Simulator,name=Apple Watch Series 5 - 44mm" | xcpretty -c
    - os: osx
      language: objective-c
      osx_image: xcode11.4
      script:
        - set -o pipefail
        - swift package generate-xcodeproj
        - xcodebuild test -scheme CGPointVector-Package -configuration Debug | xcpretty -c
        - xcodebuild test -scheme CGPointVector-Package -configuration Debug -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 11 Pro" | xcpretty -c
        - xcodebuild test -scheme CGPointVector-Package -configuration Debug -sdk appletvsimulator -destination "platform=tvOS Simulator,name=Apple TV 4K" | xcpretty -c
        - xcodebuild build -scheme CGPointVector-Package -configuration Debug -sdk watchsimulator -destination "platform=watchOS Simulator,name=Apple Watch Series 5 - 44mm" | xcpretty -c
        - xcodebuild test -scheme CGPointVector-Package -configuration Release | xcpretty -c
        - xcodebuild test -scheme CGPointVector-Package -configuration Release -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 11 Pro" | xcpretty -c
        - xcodebuild test -scheme CGPointVector-Package -configuration Release -sdk appletvsimulator -destination "platform=tvOS Simulator,name=Apple TV 4K" | xcpretty -c
        - xcodebuild build -scheme CGPointVector-Package -configuration Release -sdk watchsimulator -destination "platform=watchOS Simulator,name=Apple Watch Series 5 - 44mm" | xcpretty -c
    - os: osx
      language: generic
      osx_image: xcode10.2
      script:
        - swift --version
        - swift build
        - swift test
        - swift build -c release
        - swift test -c release
    - os: osx
      language: generic
      osx_image: xcode11
      script:
        - swift --version
        - swift build
        - swift test
        - swift build -c release
        - swift test -c release
    - os: osx
      language: generic
      osx_image: xcode11.4
      script:
        - swift --version
        - swift build
        - swift test
        - swift build -c release
        - swift test -c release
